name: Build Windows Installer
on:
  push:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Build Frontend
        working-directory: Frontend
        run: |
          npm ci
          npm run build

      - name: Copy Frontend → Spring static
        shell: bash
        run: |
          rm -rf Backend/src/main/resources/static
          mkdir -p Backend/src/main/resources/static
          cp -R Frontend/dist/* Backend/src/main/resources/static/

      - name: Build Spring Boot JAR
        working-directory: Backend
        run: .\mvnw -DskipTests package

      - name: Make Windows installer (.exe)
        working-directory: Backend
        shell: pwsh
        run: |
          $jar = (Get-ChildItem target\*.jar | Select-Object -First 1).Name
          Write-Host "Packaging $jar into installer..."
          jpackage `
            --name Fluxo `
            --app-version 1.0.0 `
            --input target `
            --main-jar $jar `
            --type exe `
            --win-shortcut `
            --win-menu `
            --icon src\main\resources\icon.ico

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fluxo-Windows-Installer
          path: Backend\*.exe

